name: trenchbroom
version: 2.0.2
summary: A modern cross-platform level editor for Quake-engine based games.
description: |
  TrenchBroom is a cross platform level editor for Quake-engine based games. It supports Quake, Quake 2, and Hexen 2 and runs on Windows (XP and newer), Mac OS X (10.6 and newer) and Linux. TrenchBroom is easy to use and provides many simple and advanced tools to create complex and interesting levels with ease.
  
  General
    - Full support for editing in 3D and in up to three 2D views
    - High performance renderer with support for huge maps
    - Unlimited Undo and Redo
    - Macro-like command repetition
    - Issue browser with automatic quick fixes
    - Point file support
    - Automatic backups
    - Free and cross platform
  Brush Editing
    - Robust vertex editing with edge and face splitting and manipulating multiple vertices together
    - Clipping tool with two and three points
    - CSG operations: merge, subtract, intersect
    - UV view for easy texture manipulations
    - Precise texture lock for all brush editing operations
    - Multiple texture collections
  Entity Editing
    - Entity browser with drag and drop support
    - Support for FGD and DEF files for entity definitions
    - Mod support
    - Entity link visualization
    - Displays 3D models in the editor
    - Smart entity property editors

confinement: strict

apps:
  trenchbroom:
    command: desktop-launch trenchbroom-editor
    plugs: [ wayland, x11, desktop, opengl, home ]

parts:
  trenchbroom:
    source: https://github.com/kduske/TrenchBroom/archive/v2.0.2.tar.gz
    source-type: tar
    source-checksum: sha1/b3ac0387b1031f0f0276c7d4f6810301dd71a1e9
    plugin: cmake
    configflags:
      - -DwxWidgets_PREFIX=$SNAPCRAFT_STAGE
    build-packages:
      - make
      - cmake
      - build-essential
      - libgtk2.0-dev
      - libjpeg-turbo8-dev
      - freeglut3-dev
      - libglew-dev
      - mesa-common-dev
      - libglm-dev
      - libxxf86vm-dev
      - libgl1-mesa-dev
      - libx11-xcb-dev
      - libxft-dev
      - libxi-dev
      - libfreeimage-dev
      - libfreetype6-dev
      - pandoc
    after: [ wxwidgets, desktop-gtk2 ]
  wxwidgets:
    source: https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.1/wxWidgets-3.1.1.tar.bz2
    source-type: tar
    source-checksum: sha1/f999c3cf1887c0a60e519214c14b15cb9bb5ea6e
    plugin: autotools
    build-packages:
      - gettext
      - libcairo2-dev
      - libexpat1-dev
      - libgtk2.0-dev
      - libjpeg-dev
      - libnotify-dev
      - libpng-dev
      - libsecret-1-dev
      - libtiff5-dev
      - libxtst-dev
      - zlib1g-dev
    override-build: |
      set -eu
      PATH="${SNAPCRAFT_STAGE}/bin:${PATH}"
      ./autogen.sh
      ./configure --prefix="${SNAPCRAFT_STAGE}" --with-gtk=2 --with-opengl
      make --jobs=$(nproc)
      make prefix="${SNAPCRAFT_PART_INSTALL}" install
    stage-packages:
      - binutils
    filesets:
      autoconf-macros:
        - share/aclocal/*
      bakefiles:
        - share/bakefile/*
      files-from-stage-packages:
        - usr/*
      executables:
        - bin/*
      headers:
        - include/*
      libraries:
        - lib/*
      localizations:
        - share/locale/*
    stage:
      - $autoconf-macros
      - $executables
      - $files-from-stage-packages
      - $headers
      - $libraries
      - $localizations
    override-stage: |
      set -eu
      snapcraftctl stage
    prime:
      - $files-from-stage-packages
      - $localizations
  wrapper:
    plugin: dump
    organize:
      trenchbroom-editor: usr/bin/trenchbroom-editor
    after: [ env ]
  env:
    plugin: nil
    stage-packages:
      - zlib1g
      - libglew1.13
      - libjpeg-turbo8
      - freeglut3
      - libxxf86vm1
      - libfreeimage3
      - libfreetype6
    after: [ trenchbroom ]
