name: trenchbroom
version: 2.0.2
grade: stable
summary: A modern cross-platform level editor for Quake-engine based games.
description: |
  TrenchBroom is a cross platform level editor for Quake-engine based games. It supports Quake, Quake 2, and Hexen 2 and runs on Windows (XP and newer), Mac OS X (10.6 and newer) and Linux. TrenchBroom is easy to use and provides many simple and advanced tools to create complex and interesting levels with ease.
  
  General
    - Full support for editing in 3D and in up to three 2D views
    - High performance renderer with support for huge maps
    - Unlimited Undo and Redo
    - Macro-like command repetition
    - Issue browser with automatic quick fixes
    - Point file support
    - Automatic backups
    - Free and cross platform
  Brush Editing
    - Robust vertex editing with edge and face splitting and manipulating multiple vertices together
    - Clipping tool with two and three points
    - CSG operations: merge, subtract, intersect
    - UV view for easy texture manipulations
    - Precise texture lock for all brush editing operations
    - Multiple texture collections
  Entity Editing
    - Entity browser with drag and drop support
    - Support for FGD and DEF files for entity definitions
    - Mod support
    - Entity link visualization
    - Displays 3D models in the editor
    - Smart entity property editors
    
  To enable Quake engines within the editor install and connect an engine:
    snap install quakespasm-beidl # or vkquake, for Quake 1
    snap install yamagi-quake2-beidl # for Quake 2
    snap connect trenchbroom:quake-engine quakespasm-beidl:quake-engine
    snap connect trenchbroom:quake2-engine yamagi-quake2-beidl:quake2-engine

confinement: strict

apps:
  trenchbroom:
    command: desktop-launch trenchbroom
    plugs: [ x11, desktop, opengl, home, removable-media ]

plugs:
  quake-modtools:
    content: quake-modtools
    interface: content
    target: $SNAP/quaketools
    default-provider: quake-toolkit:quake-modtools
  quake-engine:
    content: quake-engine
    interface: content
    target: $SNAP/quake-engine
    default-provider: quakespasm-beidl:quake-engine
  quake2-engine:
    content: quake2-engine
    interface: content
    target: $SNAP/quake2-engine
    default-provider: yamagi-quake2-beidl:quake2-engine

parts:
  trenchbroom:
    source: https://github.com/kduske/TrenchBroom.git
    source-type: git
    source-tag: v2.0.2
    plugin: cmake
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DwxWidgets_PREFIX=$SNAPCRAFT_STAGE
    build-packages:
      - make
      - cmake
      - build-essential
      - libgtk2.0-dev
      - libjpeg-turbo8-dev
      - freeglut3-dev
      - libglew-dev
      - mesa-common-dev
      - libglm-dev
      - libxxf86vm-dev
      - libgl1-mesa-dev
      - libx11-xcb-dev
      - libxft-dev
      - libxi-dev
      - libfreeimage-dev
      - libfreetype6-dev
      - pandoc
    after: [ wxwidgets, desktop-gtk2 ]
  wxwidgets:
    source: https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.1/wxWidgets-3.1.1.tar.bz2
    source-type: tar
    source-checksum: sha1/f999c3cf1887c0a60e519214c14b15cb9bb5ea6e
    plugin: autotools
    build-packages:
      - binutils
      - gettext
      - libcairo2-dev
      - libexpat1-dev
      - libgtk2.0-dev
      - libjpeg-dev
      - libnotify-dev
      - libpng-dev
      - libsecret-1-dev
      - libtiff5-dev
      - libxtst-dev
      - zlib1g-dev
    configflags:
      - --with-gtk=2
      - --with-opengl
    install-via: prefix
    filesets:
      autoconf-macros:
        - share/aclocal/*
      bakefiles:
        - share/bakefile/*
      files-from-stage-packages:
        - usr/*
      executables:
        - bin/*
      headers:
        - include/*
      libraries:
        - lib/*
      localizations:
        - share/locale/*
    stage:
      - $autoconf-macros
      - $executables
      - $files-from-stage-packages
      - $headers
      - $libraries
      - $localizations
    prime:
      - $files-from-stage-packages
      - $localizations
      - $libraries
  env:
    plugin: nil
    stage-packages:
      - zlib1g
      - libglew1.13
      - libjpeg-turbo8
      - freeglut3
      - libxxf86vm1
      - libfreeimage3
      - libfreetype6
      - libxtst6
      - libsecret-1-0
      - libice6
      - libnotify4
      - libsm6
    after: [ trenchbroom ]
